// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA2M8jGlmmtAtv5wd3D9Y1XHCh63pGhIo0',
    appId: '1:130187652547:android:49cf6c4ccdeb7be99da176',
    messagingSenderId: '130187652547',
    projectId: 'genie-on-bike-c0cc5',
    storageBucket: 'genie-on-bike-c0cc5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC8R0LB-CUb1kLXHUhjcnj8cWGglbpHS2M',
    appId: '1:130187652547:ios:2923fcdb40185c2a9da176',
    messagingSenderId: '130187652547',
    projectId: 'genie-on-bike-c0cc5',
    storageBucket: 'genie-on-bike-c0cc5.appspot.com',
    androidClientId: '130187652547-gp3m7rq9aet3q0pfgfbg13pkv21r5es2.apps.googleusercontent.com',
    iosClientId: '130187652547-a1moapf58ftovtf3cvdsh90jpqs5f2ru.apps.googleusercontent.com',
    iosBundleId: 'user.genieonbike.com',
  );
}
